server:
  port: 10001
spring:
  application:
    name: net-learning-gateway
    servlet:
      multipart:
        enabled: true
        max-file-size: 2048MB
        max-request-size: 2048MB
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
zuul:
  host:
    max-total-connections: 1000
  routes:
    net-learning-course:
      path: /cms/**
      serviceId: net-learning-course
      # 例子：将请求转发到http://localhost:31200/course
      #url: http://www.baidu.com #也可指定url，此url也可以是外网地址\
      strip-prefix: true #true：代理转发时去掉前缀，false:代理转发时不去掉前缀
#      sensitiveHeaders:  #默认zuul会屏蔽cookie，cookie不会传到下游服务，这里设置为空则取消默认的黑名单，如果设置了具体的头信息则不会传到下游服务
      #   ignoredHeaders: 默认为空表示不过虑任何头
    net-learning-fss:
      path: /fms/**
      serviceId: net-learning-fss
      strip-prefix: true
    net-learning-auth:
      path: /ams/**
      serviceId: net-learning-auth
      strip-prefix: true
    net-learning-user-auth:
      path: /ums/**
      serviceId: net-learning-user-auth
      strip-prefix: true
#  需要忽略的头部信息，不在传播到其他服务 ,H-APP-Id,Token,APPToken,token
  sensitive-headers:
  ignored-headers:
#  sensitive-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken,token,cookie,set-cookie
#  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken,token,cookie,set-cookie
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:9001/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: localhost
    instance-id: ${spring.application.name}:${server.port} #指定实例id

sequence:
  enable: true
  type: snowflake
  generate: random
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 50000  #请求连接的超时时间
  ReadTimeout: 60000 #请求处理的超时时间

feign:
  hystrix:
enabled: true

#### hystrix禁止服务超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#        timeout:
#          enabled: false

tokenName: token
tokenExpireTime: 30
cookieDomain: localhost
#cookieDomain: netlearning.com
cookiePath: /
cookieTime: 1800
