server:
  port: 40001
spring:
  application:
    name: net-learning-fss
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/netlearning-system?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5      #最小连接数量
      maxActive: 20   #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true  #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000    #连接在连接池的最小生存时间（毫秒）
  data:
    mongodb:
      uri:  mongodb://xuchang:xuchang@localhost:27017
      #uri:  mongodb://localhost:27017
      database: netlearning_cms
    freemarker:
      cache: false  #关闭模板缓存，方便测试
      settings:
        template_update_delay: 0
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      virtualHost: /
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1

sequence:
  enable: true
  type: snowflake
  generate: random
pagehelper:
  helper-dialect: mysql
mybatis:
  mapper-locations: classpath:com.netlearning.fss.mapper/*.xml

###服务名称(服务注册到eureka名称)
###服务注册到eureka地址

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:9001/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id

feign:
  hystrix:
enabled: true

#### hystrix禁止服务超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

fss_file_path: D:\NetworkLearningPlatform\upload

secretId: AKIDqFTZF0JjUuATGexY1eoS0UnU2aIAlhIh
secretKey: OS7NSSN8XjlFYhK6haRZHtkeNkwk8OUX
storageRegion: ap-guangzhou
