server:
  port: 31003
spring:
  application:
    name: netlearning-file
  data:
    mongodb:
      uri:  mongodb://xuchang:xuchang@localhost:27017
      #uri:  mongodb://localhost:27017
      database: netlearning_file
#SpringMVC上传文件配置
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      #location:
      # 最大支持文件大小
      max-file-size: 5MB
      # 最大支持请求大小
      max-request-size: 30MB
      


#netlearning:
#  fastdfs:
#    connect_timeout_in_seconds: 5
#    network_timeout_in_seconds: 30
#    charset: UTF-8
#    tracker_servers: 134.175.30.90:22122
netlearning:
  fastdfs:
    connect_timeout_in_seconds: 5
    network_timeout_in_seconds: 30
    charset: UTF-8
    tracker_servers: 134.175.30.90:22122
###服务名称(服务注册到eureka名称)
###服务注册到eureka地址

###集群地址defaultZone以，区分
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  # 心跳检测检测与续约时间
  # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  instance:
    ###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
    ####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:V@project.version@