server:
  port: 31003
spring:
  application:
    name: net-learning-filesystem
  data:
    mongodb:
      uri:  mongodb://xuchang:xuchang@localhost:27017
      #uri:  mongodb://localhost:27017
      database: netlearning_file
#SpringMVC上传文件配置
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      #location:
      # 最大支持文件大小
      max-file-size: 5MB
      # 最大支持请求大小
      max-request-size: 30MB



netlearning:
  fastdfs:
    connect_timeout_in_seconds: 5
    network_timeout_in_seconds: 30
    charset: UTF-8
    tracker_servers: 134.175.30.90:22122
###服务名称(服务注册到eureka名称)
###服务注册到eureka地址

###集群地址defaultZone以，区分
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:9001/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id
