###eureka 服务端口号
server:
  port: ${PORT:9001}
###服务注册名称
eureka:
  instance:
    hostname: netlearning-eureka-server
###客户端调用地址
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
###因为该应用为注册中心，不会注册自己
    register-with-eureka: false
###因为自己为注册中心 ,不会去在该应用中的检测服务
    fetch-registry: false

spring:
  cloud:
    inetutils:
      ## 设置网络超时
      timeout-seconds: 5
      ## 忽略网卡
      ignored-interfaces:
        - VMware Virtual Ethernet Adapter for VMnet1
        - VMware Virtual Ethernet Adapter for VMnet8
        - Hyper-V Virtual Ethernet Adapter
        - Hyper-V Virtual Ethernet Adapter #2
    refresh:
      refreshable: none
