server:
  port: 31001
spring:
  application:
    name: netlearning-service-manage-cms
  cloud:
    inetutils:
      ## 设置网络超时
      timeout-seconds: 5
      ## 忽略网卡
      ignored-interfaces:
        - VMware Virtual Ethernet Adapter for VMnet1
        - VMware Virtual Ethernet Adapter for VMnet8
        - Hyper-V Virtual Ethernet Adapter
        - Hyper-V Virtual Ethernet Adapter #2
    refresh:
      refreshable: none
  data:
    mongodb:
      uri:  mongodb://xuchang:xuchang@localhost:27017
      #uri:  mongodb://localhost:27017
      database: netlearning_cms
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
###服务名称(服务注册到eureka名称)

###服务注册到eureka地址

###集群地址defaultZone以，区分
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:9001/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id
